In [1]:
#### Order by a Variable ####

# Importing necessary libraries
import pandas as pd

# Load the CSV file into a DataFrame
suppliers_df = pd.read_csv('Suppliers.csv')

# Sort the DataFrame by 'SupplierName' in ascending order
sorted_suppliers = suppliers_df.sort_values(by='SupplierName', ascending=True)

# Calculate the number of observations
num_observations = len(sorted_suppliers)

# Print the number of observations
print(f"Number of observations (Ascending): {num_observations}")

# Display the resulting DataFrame with all columns
display(sorted_suppliers.style.hide(axis = "index"))

# Add a few blank lines
print("\n\n")

# Sort the DataFrame by 'SupplierName' in ascending order
sorted_suppliers = suppliers_df.sort_values(by='SupplierName', ascending=False)

# Calculate the number of observations
num_observations = len(sorted_suppliers)

# Print the number of observations
print(f"Number of observations (Descending): {num_observations}")

# Display the resulting DataFrame with all columns
display(sorted_suppliers.style.hide(axis = "index"))

Number of observations (Ascending): 29

Number of observations (Descending): 29