In [1]:
#### Select Variables ####

# Importing necessary libraries
import pandas as pd

# Load the CSV file into a DataFrame
suppliers_df = pd.read_csv('Suppliers.csv')

# Set the option to display all rows (change 1000 to your desired number)
pd.set_option('display.max_rows', 1000)

# Calculate the number of observations
num_observations = len(suppliers_df)

# Print the number of observations
print(f"Number of observations: {num_observations}")

# Display the 'Country' column in a tabular format
display(suppliers_df[['Country']].style.hide(axis="index"))

print(suppliers_df['Country'][9])
print(suppliers_df['Country'][0])
print(suppliers_df['Country'][num_observations-1])

Number of observations: 29

Brazil
UK
Canada